services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecotrack-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecotrack-backend
    ports:
      - "5000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3


  prometheus:
    image: prom/prometheus:latest
    container_name: ecotrack_prometheus    
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ecotrack_grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ecotrack_node_exporter
    ports:
      - "9100:9100"
    restart: unless-stopped



volumes:
  grafana_data: