global:
  scrape_interval: 15s  
  
scrape_configs:
  - job_name: "prometheous"
    static_configs:
      - targets: [prometheous:9090]

  - job_name: "node_exporter"
    static_configs:
      - targets: [node_exporter:9100]